### ISSUE TITLE
Pulador

### ISSUE THREAD

**Issue by rodigu** [tecMTST/modelo-godot-3.6#13]
## Relações

- _relações com outros issues/componentes_

## Interfaces

- _inclua links para arquivos relevantes_

### Sinais

- inicio_de_pulo
- topo_do_pulo
- fim_do_pulo

### Variáveis

- `export forca: float`
- `export multiplicador_de_gravidade: float`
- `export multiplicador_de_queda: float`
- `export tempo_de_coyote: float`
- `export buffer_de_pulo: float`
- `export modo: Enum = {Autonomo, Puro}`
- `export entrada_do_pulo: String`
- `export pulo_variavel: Boolean`

### Funções

- `iniciar_pulo()`
- `pular() -> Vector2`
- `finalizar_pulo()`
- `forcar_caida()`

## Efeitos Colaterais

- dependendo do modo, altera propriedades do responsavel

## Referências

- _referências externas_

**Comment by Kelvysb** [comment]
PR: https://github.com/tecMTST/modelo-godot-3.6/pull/15
