### ISSUE TITLE
Shader teste de estresse

### ISSUE THREAD

**Issue by rodigu** [tecMTST/modelo-godot-3.6#19]
Referencia: https://godotshaders.com/

**Comment by ClockWritesDev** [comment]
*Escolhi a dedo 5 Shaders que podem ser utilizados em diversas instâncias para o pessoal do design.*


**Foliage animation:**

Baseado nesse shader: https://godotshaders.com/shader/foliage-animation/

Obs: Eu posso traduzir o código dele para o godot 3.6 já que ele é feito para o 4.

https://github.com/Jose-Herbert/modelo-godot3.6.git  Ta na Branch_TesteShader

- [x] Done



**Hit Flash animation:**

Baseado nesse shader: https://godotshaders.com/shader/flash-shader/

Obs: Efeito de hit para Sprites2D.

https://github.com/Jose-Herbert/modelo-godot3.6.git  Ta na Branch_TesteShader

- [x] Done 



**Cel Shading:** X

**Parallax Shader**
Obs: Tive que trocar o efeito de cel shading para o de parallax, pois o efeito anterior não estava aparecendo corretamente no editor.

- [x] Done



**God Rays :**

Baseado nesse shader: https://godotshaders.com/shader/god-rays/

Obs: Godrays para deixar iluminação dinâmica e "realista" se a equipe de design for levar esse estilo para o
projeto.

- [x] Done



**Highlight Sprite :**

Baseado nesse shader: https://godotshaders.com/shader/2d-item-highlight-shader/

Obs: Highlight de itens para facilitar visibilidade.

https://github.com/Jose-Herbert/modelo-godot3.6.git  Ta na Branch_TesteShader

- [x] Done
