### ISSUE TITLE
ControleDeSwipe

### ISSUE THREAD

**Issue by rodigu** [tecMTST/modelo-godot-3.6#23]
## Relações

- _relações com outros issues/componentes_

## Interfaces

- evento pra cada direcao
- forma de definir angulo de tolerancia pra cada direcao

## Efeitos Colaterais

- _efeitos colaterias do componente_

## Referências

- _referências externas_

**Comment by ClockWritesDev** [comment]
Obs: O Input já se comporta como um evento, daria para utilizar um ` func _Input(event):`
para captar a coordenada de drag na tela e fazer uma tolerancia dessa drag.

o input retornaria como uma variavel que contem o vetor 2 de cada swipe e transformaria em um signal para o player ir em direção ao Position2D.

Porém isso vai depender de como funciona o teu touchdrag.
