### ISSUE TITLE
ControleDeFaixas

### ISSUE THREAD

**Issue by rodigu** [tecMTST/modelo-godot-3.6#24]
## Relações

- #23 

## Interfaces

- crianca do jogador
- referencias das faixas (Vector2D)
- mover esquerda, mover direita

### Variáveis

- indice_faixa_do_parente: int
- lista_de_faixas: Array<Vector2>

### Funções

- adicionar_faixa(faixa: Vector2D)
- mover_esquerda() -> bool
- mover_direita() -> bool
- processar() -> Vector2

## Efeitos Colaterais

- _efeitos colaterias do componente_

## Referências

- _referências externas_

**Comment by Kelvysb** [comment]
https://github.com/tecMTST/modelo-godot-3.6/pull/26
