### ISSUE TITLE
Erro com #13

### ISSUE THREAD

**Issue by rodigu** [tecMTST/modelo-godot-3.6#25]
#13
![image](https://github.com/tecMTST/modelo-godot-3.6/assets/58960796/5cfc3cd2-c325-4545-8f9d-2b612047e76e)

**Comment by rodigu** [comment]
![image](https://github.com/tecMTST/modelo-godot-3.6/assets/58960796/ecead65f-8bd0-4c01-8035-a2e446070e5e)

**Comment by ClockWritesDev** [comment]
o godot 3.6 não suporta svg kkkkkk ai ele não ta conseguindo da parse porcausa do svg

**Comment by Kelvysb** [comment]
umm vou dar uma olhada (na minha maquina deu isso mas depois parou, abri umas 4 vezes)
o svg carregou ok, deve ter sido um problema com o arquivo .import, acho que ele não deveria ter subido, foi commitado antes da atualização do gitignore, vou checar isso.

**Comment by Kelvysb** [comment]
PR: https://github.com/tecMTST/modelo-godot-3.6/pull/27
